[package]
name = "bakkuraito"
authors = ["NoPreserveRoot"]
description = "A small tool to adjust backlights on Linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
